name: tester

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'runatlantis.io/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

    branches:
      - "main"
    paths-ignore:
      - 'runatlantis.io/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: runner / gotest
    runs-on: ubuntu-22.04
    container: ghcr.io/runatlantis/testing-env:latest
    steps:
      - uses: actions/checkout@v3
      - run: make test-all

      ###########################################################
      # Notifying #contributors about test failure on main branch
      ###########################################################
      - name: failure run notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_LAUNCHING_CHANNEL_WEBHOOK }}
        uses: Ilshidur/action-slack@2.1.0
        with:
          args: |
            :scream: :scream: :scream: gotest job <https://github.com/runatlantis/atlantis/actions/runs/${{github.run_id}}|#${{github.run_number}}> failed!
